#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -f ~/.Xresources ]; then
    xrdb -merge ~/.Xresources
fi

session=${1:-xmonad}
case $session in
    xmonad)
    # Turn off Touchpad
    xinput --disable 'ETPS/2 Elantech Touchpad'
    # Start urxvt daemon
    urxvtd -q -f -o
    # Start xscreensaver daemon
    xscreensaver -no-splash &
    # Enable numlock on startup
    numlockx &
    # Start pulseaudio
    start-pulseaudio-x11
    # Start easystroke
    easystroke &

    # Set the cursor
    xsetroot -cursor_name left_ptr
    # Set Spanish keyboard layout
    setxkbmap -layout es
    # Set wallpaper
    feh --bg-fill $HOME/Images/Wallpapers/TinyGalaxy.jpg
    # Start notification server (dunst)
    dunst &
    # Start status bar engine
    ${HOME}/.config/lueng/lueng.sh &
    # Start xcompmgr for transparency
    xcompmgr &

    # Start xmonad
    # Start dzen with its socket (doesn't work yet)
    #nc -k -l -U ${HOME}/.xmonad/log.soc | dzen2 -ta l -bg '#161616' -fn 'Terminus:size=8' -w 600 -e '' -dock &
    # Actually start xmonad
    exec xmonad
    ;;
    gnome)
    exec gnome-session
    ;;
    *)
    exec $1
    ;;
esac

# ...or the Window Manager of your choice
